routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::post('/webhooks/inbound', 'WhatsappController@incoming');

Route::get('/', function () {
    return view('login');
})->name('home');
Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('mlogin', 'Auth\LoginController@login')->name('mlogin');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::get('create/{client_id}/{process_id}/{step_id}', ['as' => 'messages.client', 'uses' => 'MessagesController@client_create']);
    Route::get('create/{client_id}/{related_party_id}', ['as' => 'messages.relatedparty', 'uses' => 'MessagesController@relatedparty_create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

Route::get('powerpoint', 'ReportController@powerpoint')->name('powerpoint');
Route::get('reports/task', 'ReportController@task')->name('reports.task');
Route::get('reports/my-work-day', 'ReportController@myworkday')->name('reports.myworkday');
Route::get('reports/my-work-day/{card_id}/details', 'ReportController@getMyworkdayItem');
Route::post('reports/my-work-day/{card_id}/save', 'ReportController@saveMyworkdayItem');
Route::any('reports/my-work-day/card/update_status/{card}', 'CardController@updateWorkDayStatus');
Route::any('reports/my-work-day/task/update_status/{task}', 'TaskController@updateWorkDayStatus');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('profile/{user?}', 'UserController@profile')->name('profile');
Route::get('settings', 'UserController@settings')->name('settings');
Route::post('settings/password', 'UserController@handlePassword')->name('settings.password');
Route::post('settings/profile', 'UserController@handleProfile')->name('settings.profile');
Route::post('settings/notifications', 'UserController@handleNotifications')->name('settings.notifications');

Route::any('/', 'HomeController@index')->name('home');
Route::any('/home', 'HomeController@index');
Route::get('recents', 'HomeController@recents')->name('recents');
Route::any('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::any('progress', 'HomeController@progress')->name('progress');
Route::get('calendar', 'HomeController@calendar')->name('calendar');
Route::get('help', 'HelpController@create')->name('help.create');
Route::post('help', 'HelpController@store')->name('help.store');

Route::resource('emaillogs', 'EmailLogsController');
Route::get('emaillogs/{email_id}', 'EmailLogsController@show')->name('emaillogs.show');

/*Route::get('storage/crf', 'AssetController@getCrf')->name('crf_client');*/
Route::get('storage/avatar', 'AssetController@getAvatar')->name('avatar');
Route::get('storage/document', 'AssetController@getDocument')->name('document');
Route::get('storage/template', 'AssetController@getTemplate')->name('template');

Route::get('clients/amlreviewed', 'ClientController@amlReviewed')->name('clients.amlreviewed');
Route::get('clients/amlapproved', 'ClientController@amlApproved')->name('clients.amlapproved');
Route::get('clients/amlreviewedandapproved', 'ClientController@amlReviewedAndApproved')->name('clients.amlreviewedandapproved');
Route::get('clients/completed/{step_id}', 'ClientController@completed')->name('clients.completed');

Route::get('clients/xlsexport','ClientController@xlsExport')->name('clients.xlsexport');
Route::resource('clients', 'ClientController');

Route::post('clients/{client}/updates','ClientController@update')->name('clients.savedetail');
Route::get('clients/{client}/avatar','ClientController@generateAvatar')->name('clients.avatar');
Route::get('clients/{client}/progress','ClientController@progress')->name('clients.progress');
Route::get('clients/{client}/processes/{process}/{step}','ClientController@processes')->name('clients.processes');
Route::post('clients/{client}/progress','ClientController@storeProgress')->name('clients.storeprogress');
Route::post('clients/{client}/actions','ClientController@storeActions')->name('clients.storeactions');
Route::post('clients/{client}/progress/{process?}/{step?}','ClientController@completeStep')->name('clients.completestep');
Route::post('clients/{client}/progress2/{process?}/{step?}','ClientController@completeStep2')->name('clients.completestep2');
Route::get('clients/{client}/progress/{process}/{step}','ClientController@stepProgress')->name('clients.stepprogress');
Route::get('clients/{client}/progressaction/{process}/{step}/{action_id}','ClientController@stepProgressAction')->name('clients.stepprogressaction');
Route::get('clients/{client}/documents/{process}/{step}','ClientController@documents')->name('clients.documents');
Route::get('clients/documents/toggleclientportal/{document_id}','ClientController@toggleClientPortal')->name('clients.documents.toggleclientportal');
/*Route::get('clients/{client}/forms','ClientController@forms')->name('clients.forms');*/
Route::get('clients/{client}/edit/{process}/{step}','ClientController@edit')->name('clients.edit');
/*Route::get('clients/{client}/forms/uploadform','ClientController@uploadforms')->name('forms.uploadforms');
Route::get('clients/{client}/forms/editform/{formid}','ClientController@edituploadforms')->name('forms.editforms');
Route::post('clients/{client}/forms/storeform','ClientController@storeuploadforms')->name('forms.uploadstore');
Route::post('clients/{clientid}/forms/{formid}/formupdate','ClientController@updateuploadforms')->name('forms.formupdate');
Route::get('clients/{client}/forms/createcrf','ClientController@createCrfForm')->name('forms.createcrf');
Route::get('clients/{client}/forms/editcrf/{formid}','ClientController@editCrfForm')->name('forms.editcrf');
Route::get('clients/{client}/forms/signcrf/{formid}','ClientController@signCrfForm')->name('forms.signcrf');
Route::post('clients/{clientid}/forms/{formid}/updatecrf','ClientController@updateCrfForm')->name('forms.updatecrf');
Route::post('clients/{client}/forms/storecrf','ClientController@saveCrfForm')->name('forms.storecrf');
Route::get('clients/{client}/forms/{formid}/generatecrf','ClientController@generateCrfForm')->name('forms.generatecrf');
Route::get('clients/{client}/forms/upload','ClientController@saveCrfForm')->name('forms.upload');
Route::get('clients/{client}/forms/delete/{formid}','ClientController@deleteCrfForm')->name('crfforms.destroy');*/
Route::get('clients/{client_id}/completed/{step_id}/{newdate}','ClientController@complete')->name('clients.complete');
Route::get('clients/{client_id}/uncompleted/{step_id}','ClientController@uncomplete')->name('clients.uncomplete');
Route::get('clients/{client_id}/changecompleted/{step_id}/{newdate}','ClientController@changecomplete')->name('clients.changecomplete');
Route::post('clients/{client}/sendnotification/{activity?}','ClientController@sendNotification')->name('clients.sendnotification');
Route::post('clients/{client}/sendtemplate/{activity?}','ClientController@sendTemplate')->name('clients.sendtemplate');
Route::post('clients/{client}/senddocument/{activity?}','ClientController@sendDocument')->name('clients.senddocument');
Route::get('clients/{client}/viewtemplate/{template?}','ClientController@viewTemplate')->name('clients.viewtemplate');
Route::get('clients/{client}/viewdocument/{document?}','ClientController@viewDocument')->name('clients.viewdocument');
/*Route::put('clients/{client}/follow','ClientController@follow')->name('clients.follow');*/
Route::get('clients/{client}/activityprogress/{process}/{step}','ClientController@activityProgress')->name('clients.activityprogress');
Route::get('clients/{client}/getcomments','ClientController@getComment')->name('clients.getcomment');
Route::post('clients/{client}/storecomment','ClientController@storeComment')->name('clients.storecomment');
Route::post('clients/deleteclientcomment/{comment}','ClientController@deleteComment')->name('clients.deletecomment');
Route::post('clients/{client}/progressing','ClientController@storeProgressing')->name('clients.progressing');
/*Route::post('clients/{client}/qa','ClientController@storeQA')->name('clients.qa');*/
/*Route::post('clients/{client}/qacomplete','ClientController@completeQA')->name('clients.qacomplete');
Route::post('clients/{client}/qaprod','ClientController@storeProd')->name('clients.qaprod');*/
Route::post('clients/{client}/approval','ClientController@approval')->name('clients.approval');
Route::post('clients/{client}/senddocuments/{activity?}','ClientController@sendDocuments')->name('clients.senddocuments');

Route::post('clients/{client}/sendmail','ClientController@sendMail')->name('clients.sendMail');

resources/views/calendar.blade.php
@extends('layouts.app')

@section('title') Calendar @endsection

@section('header')
    <h1><i class="fa fa-calendar-o"></i> @yield('title')</h1>
@endsection

@section('content')
    <form class="form-inline mt-3">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','company'=>'Branch'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; from &nbsp;
        {{Form::select('s',['all'=>'All Time','mine'=>'My','company'=>'Branch'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fa fa-search"></i></span>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control','placeholder'=>'Search...'])}}
        </div>
    </form>

    <hr>

    <div id="calendar">
    </div>
@endsection

@section('extra-css')
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css'/>
@endsection

@section('extra-js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js'></script>
    <script>
        $(document).ready(function() {
            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'listDay,month,agendaWeek,agendaDay'
                },eventSources: [

    // your event source
    {
      events: [ // put the array in the `events` property
        {
          title  : 'event1',
          start  : '2018-04-01'
        },
        {
          title  : 'event2',
          start  : '2018-04-05',
          end    : '2018-04-07'
        },
        {
          title  : 'event3',
          start  : '2018-04-09T12:30:00',
        }
      ],
      color: 'black',     // an option!
      textColor: 'yellow' // an option!
    }

    // any other event sources...

  ]

            })

        });
    </script>
@endsection

resources/views/dashboard.blade.php
@extends('adminlte.default')

@section('title') Dashboard @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        <hr>
    </div>
@endsection

@section('content')
    <div class="container-fluid chart-wrapper">
        <div class="rotate2 height-chart text-center">
            <p>Pipeline and Performance</p>
        </div>
        <div>
            <!---->
            <canvas id="pipeline-performance" width="429" height="280"></canvas>
        </div>
        <div class="align-middle" style="padding-right: 50px;">
            <div class="table-responsive">
                <table class="table table-sm text-right">
                    <thead>
                    <tr>
                        <th>AUM</th>
                        <th>Revenue</th>
                        <th>Revenue (Ongoing)</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>R2,000,000</td>
                        <td>R10,000</td>
                        <td>R10,000</td>
                    </tr>
                    <tr>
                        <td>R1,500,000</td>
                        <td>R5,000</td>
                        <td>R5,000</td>
                    </tr>
                    <tr>
                        <td>R100,000</td>
                        <td>R350,000</td>
                        <td>R350,000</td>
                    </tr>
                    <tr>
                        <td>R2,000,000</td>
                        <td>R120,000</td>
                        <td>R120,000</td>
                    </tr>
                    <tr>
                        <td>R450,000</td>
                        <td>R80,000</td>
                        <td>R80,000</td>
                    </tr>
                    <tr>
                        <td>R5,000,000</td>
                        <td>R123,000</td>
                        <td>R123,000</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="container-fluid mt-5 clearfix">
        <!--<div class="col-md-1">
          <div class="rotate">
              <p>Tasks</p>
          </div>
        </div>-->
        <!--<div class="text-center">-->
        <div class="rotate2 float-left text-center" style="position: relative;top:40px;">
            <p>Tasks</p>
        </div>
        <div class="shadow task text-center">
            <div class="row clearfix mb-2">
                <div class="col-md-6">
                    <img src="{!! asset('img/task-bell.svg') !!}" alt="Tasks Bell">
                </div>
                <div class="col-md-6 count">
                    19
                </div>
            </div>
            <p>My Overdue Tasks</p>
        </div>
        <!--</div>
        <div class="text-center">-->
        <div class="shadow task text-center">
            <div class="row clearfix mb-2">
                <div class="col-md-6">
                    <img src="{!! asset('img/task-checklist.svg') !!}" alt="Tasks Checklist">
                </div>
                <div class="col-md-6 count">
                    19
                </div>
            </div>
            <p>My Tasks for Today</p>
        </div>
        <!--</div>
        <div class="text-center">-->
        <div class="shadow task text-center">
            <div class="row clearfix mb-2">
                <div class="col-md-6">
                    <img src="{!! asset('img/future-tasks.svg') !!}" alt="Future Tasks Checklist">
                </div>
                <div class="col-md-6 count">
                    22
                </div>
            </div>
            <p>My Future Tasks</p>
        </div>
        <!--</div>
        <div class="text-center">-->
        <div class="shadow task text-center">
            <div class="row clearfix mb-2">
                <div class="col-md-6">
                    <img src="{!! asset('img/delegated-tasks.svg') !!}" alt="Delegated Tasks Checklist">
                </div>
                <div class="col-md-6 count">
                    94
                </div>
            </div>
            <p>Delegated Tasks</p>
        </div>
        <!--</div>-->
    </div>
    <div class="container-fluid my-5 ">
        <!--<div class="col-md-1">-->
        <div class="rotate2 float-left  text-left" style="position: relative;left:-20px;top:40px;">
            <p>Interactions</p>
        </div>
        <!--</div>-->
        <!--<div class="col-md-2 text-center">-->
        <div class="shadow task2 text-center" style="margin-left: -40px;">
            <div class="row clearfix mb-2">
                <div class="col-md-6">
                    <img src="{!! asset('img/calendar-1.svg') !!}" alt="Calendar">
                </div>
                <div class="col-md-6 count">
                    3
                </div>
            </div>
            <p>My Overdue Tasks</p>
        </div>
        <!--</div>-->
        <!--<div class="col-md-2 text-center">-->
        <div class="shadow text-center task2">
            <div class="row clearfix mb-2">
                <div class="col-md-6">
                    <img src="{!! asset('img/closing-appoitment.svg') !!}" alt="Closing Appointments">
                </div>
                <div class="col-md-6 count">
                    7
                </div>
            </div>
            <p>Closing Appointments</p>
        </div>
        <!--</div>
        <div class="col-md-2 text-center">-->
        <div class="shadow text-center task2">
            <div class="row clearfix mb-2">
                <div class="col-md-6">
                    <img src="{!! asset('img/review-appointments.svg') !!}" alt="Review Appointments">
                </div>
                <div class="col-md-6 count">
                    7
                </div>
            </div>
            <p>Review Appointments</p>
        </div>
        <!--</div>
        <div class="col-md-2 text-center">-->
        <div class="shadow task2 text-center">
            <div class="row clearfix mb-2">
                <div class="col-md-6">
                    <img src="{!! asset('img/fyc-icon.svg') !!}" alt="Average FYC Size Accepted">
                </div>
                <div class="col-md-6 count">
                    R4,000
                </div>
            </div>
            <p>Average FYC Size Accepted</p>
        </div>
        <!--</div>
        <div class="col-md-2 text-center">-->
        <div class="shadow task2 text-center">
            <div class="row clearfix mb-2">
                <div class="col-md-6">
                    <img src="{!! asset('img/aum-icon.svg') !!}" alt="Average AUM Size Accepted">
                </div>
                <div class="col-md-6 count">
                    R600K
                </div>
            </div>
            <p>Average AUM Size Accepted</p>
        </div>
        <!--</div>-->
    </div>
@endsection

@section('extra-js')

@endsection

resources/views/insight.blade.php
@extends('adminlte.default')

@section('title') Insight @endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
    </div>
@endsection

@section('content')
    <div class="container-fluid">
    <blackboard-insight add-user-link="{{route('clients.create')}}"></blackboard-insight>
    </div>
@endsection

resources/views/recents.blade.php
@extends('flow.default')

@section('title') Recents @endsection

@section('content')
    <div class="content-container page-content">
        <div class="row col-md-12 h-100">
            <div class="container-fluid container-title">
                <h3>@yield('title')</h3>
            </div>
            <div class="container-fluid container-content">
                <div class="table-responsive ">
                    <table class="table table-sm table-bordered blackboard-recents">
                        <thead>
                        <tr>
                            <th colspan="3">
                                Recent Applications
                                <a href="{{route('clients.index')}}" class="btn btn-primary btn-sm float-right"><i class="fa fa-eye"></i> View all</a>
                            </th>
                        </tr>
                        <tr>
                            <th>
                                Client
                            </th>
                            <th>
                                Application
                            </th>
                            <th>
                                Section
                            </th>
                        </tr>
                        </thead>
                        @forelse($clients as $client)
                            <tr>
                                <td>
                                    <a href="{{route('clients.show',[$client->client_id,$client->process_id,$client->step_id])}}">{{($client->client->first_name)}} {{($client->client->last_name)}}</a>
                                </td>
                                <td>
                                    <a href="{{route('clients.show',[$client->client_id,$client->process_id,$client->step_id])}}">{{$client->process->name}}</a>
                                </td>
                                <td>
                                    <a href="{{route('clients.show',[$client->client_id,$client->process_id,$client->step_id])}}">{{$client->step->name}}</a>
                                    <span class="float-right text-muted"><small><i class="fa fa-clock-o"></i> {{$client->updated_at}}</small></span>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3">No recent applications</td>
                            </tr>
                        @endforelse
                    </table>
        </div>
            </div>
        </div>
    </div>
@endsection